### ISSUE TITLE
Keras?

### ISSUE THREAD

**Issue by amrrs** [anishsingh20/Adaline-vs-MLP#1]
To get this running, You have had installed Keras via Pip before loading it in RStudio?

**Comment by anishsingh20** [comment]
Yes , actually for implementing MLP in R , I have used keras and tensorflow as the backend engine . Then for using perceptron network , I have simply made a custom function. So first you have to install keras for implementing MLP . 

`install.packages(keras)` to install keras in R , then `require(keras)` to load and start using the package methods and functions.  R now has a keras and tensorflow packages available to implement and experiment with lots of deep neural networks.

**Comment by amrrs** [comment]
Thanks, To install via `pip` Python is also required right? So ultimately this is just a wrapper around Python Keras?

**Comment by anishsingh20** [comment]
Yes, actually in the backend python's `numpy` package is being used by `keras` package. So yes you need to have python or anaconda installed, only then you will be able to install  and use `keras` in R.

**Comment by amrrs** [comment]
Thanks @anish that's the validation I was looking for.
